### ISSUE TITLE
More bugs

### ISSUE THREAD

**Issue by Diarandor** [wrightmat/zbom#20]
Hi! I played a bit to your game and I found these problems. I hope this helps.

-Near the boss of the first level there is a chest with a jade and an entrance to the level. But the entrance does not work and you get stuck there (I was forced to save and reset the game).

-I finished level 1 and got the world map. But in the menu I still have the map of level 1 instead. Saving and closing the game does not seem to repair this bug.

- I also got this error in error.txt.
Error: In timer callback: [string "enemies/moth.lua"]:77: attempt to call global 'random' (a nil value)

**Comment by wrightmat** [comment]
- I believe I know which area you're talking about, and I just tested and had no problems. Do you have more details about this?

- The menu was a known issues because of the indoor/outdoor nature of the dungeon (that map is technically still part of the dungeon), and I didn't think I'd be able to fix it, but I just came up with a work-around that took care of it!

- Thanks for the error.txt message - that has been fixed as well.
