### ISSUE TITLE
NPC who don't talk

### ISSUE THREAD

**Issue by proutout** [wrightmat/zbom#34]
Two of NPC in Saria's village don't talk to you and one ruto in septen heights
I'll send pictures of the houses
![image](https://cloud.githubusercontent.com/assets/16241277/11746066/528eada0-a01c-11e5-9202-efb8cba96fd2.png)

**Comment by proutout** [comment]
![image](https://cloud.githubusercontent.com/assets/16241277/11746108/95da4b00-a01c-11e5-8c46-611b94945f2f.png)

**Comment by proutout** [comment]
![image](https://cloud.githubusercontent.com/assets/16241277/11746138/bacf50ae-a01c-11e5-9c70-6eb8ad69326b.png)

**Comment by wrightmat** [comment]
My brother and I are working on creating about 40 NPCs with full dialog and personality to fill the northern area of Hyrule. This will likely be for the 0.8 release, since I'll now do a release for all of these fixes first. In the mean time, I'll add some filler text for the two Kokiri since I have them there!
