### ISSUE TITLE
Change the day/night interval?

### ISSUE THREAD

**Issue by wrightmat** [wrightmat/zbom#66]
The original intention with the day/night system was to have 1 hour of in-game time equal 1 minute of real-time. When the "failed to convert software surface" memory leak was encountered, this was changed to half-time (1 minute of real-time is equal to 2 hours of in-game) in order to mitigate the risk of the game crashing.

I'm not sure whether it's better to change it back to the 1 to 1 time, so I'll leave this open for discussion.

**Comment by MetalES** [comment]
If you plan to do time-related side quests where approximate time is required, I'll definately recommand you to use 1:1 time flow

**Comment by wrightmat** [comment]
None of the side-quests are truly time-related, unless more are added later. A few require you to do things at any point during the night, but that's all.

**Comment by MetalES** [comment]
The thing is, I didn't really understand why you create the surfaces in on_draw() and create a such huge surface (1120) while a local variable containing the surface in initialize maps and a 320x240 surface is relatively enough

That means that the surface is rebuild at each frame and dealing with a such huge amount of pixels might be performance-killing on older machines

Plus it would fix the lantern weird effect in Hyrule field ^^

this is how you can make it


local function initialize_maps()

local shadow = sol.surface.create(320, 240)
local light = sol.surface.create(320, 240)

local light_sprites = {
  torch = sol.sprite.create(path),
  each animations goes here
}

function map_metatable:on_draw(dst)
    local hero = game:get_hero()
    local cam_x, cam_y = game:get_map():get_camera():get_position()
    local x, y = hero:get_position()
  
    -- Rebuild the light surface
    light:clear()
  
    -- Next, this section is about entities.
    local map = game:get_map()
  
    for e in map:get_entities("torch_") do
      if e:is_enabled() and e:get_sprite():get_animation() == "lit" and e:get_distance(hero) <= 300 then
        local xx,yy = e:get_position()
        light_sprites.torch:draw(self.light, xx - cam_x, yy - cam_y)
      end
    end

    light:draw(shadow)
    shadow:draw(dst)
end

It does the same thing, except that animations are played nicely and the lantern light effect would follow Link properly

**Comment by wrightmat** [comment]
Thanks MetalES! I changed the script to reflect what you suggested, and the hero lantern tracking is indeed better but now the lights move/trail when the hero moves. Would you mind looking at it to see if there are further improvements that can be made?

**Comment by MetalES** [comment]
fot the trail issue (I got it too), just clear the shadow surface before rebuilding the light one, I don't really know what and how this anomaly is possible 

Or another solution: a custom function to fill the shadow surface when needed, for example: dark rooms, so the dark room system is handled by the quest_manager

Because I see that in some of your map script, you re-create the light system that is already done in quest_manager, for example, map id 202, so the game is confused

You can take an example of how I've done it here

https://github.com/MetalES/Project-Zelda/blob/master/data/scripts/gameplay/screen/tone_manager.lua

You might see something like this in on_draw()

  if mr ~= nil then
      -- We are in a map where tone are defined (dark rooms for example)
	  self.shadow:clear() 
      self.shadow:fill_color{mr, mg, mb, ma}
    elseif self.time_system and mr == nil then
      -- We are outside
      self.shadow:fill_color{cr, cg, cb, 255}
    elseif not self.time_system and mr == nil then
      -- The map has undefined tone.
      self.shadow:fill_color{255, 255, 255, 255}
    end

mr is the overriden tone and the effect is done instantly, it is disabled automatically when mr is equal to nil, and the effects are perfectly displayed, this is how I got rid of the trail issue

**Comment by MetalES** [comment]
You might need some workarround to make it functionnal with your project because we use different ways to handle time but that should do it

But at the end, you'll come with a more versatile script that automatically handle dark rooms only if mr have a value

You can see it in action here
https://www.youtube.com/watch?v=vbwCxAdecEU&feature=youtu.be

**Comment by wrightmat** [comment]
I'll definitely take a look at this - thanks so much! Do you have an example of a map in your project that uses the "mr not being nil" functionality to display a different tone on a particular map?

**Comment by wrightmat** [comment]
Alright, the new system is definitely much better than my old one. You're awesome, MetalES :)

One thing I've probably messed up in the conversion, but I can't figure out. When I change maps using the scrolling transition, the tone in the old map resets while the tone on the new map is fine. It makes the transition look really bad because at night the old map is clear (once the transition starts) and the new map has the correct tone.

I'm also not sure the transitions are happening correctly - the tone seems to change pretty much instantly. Probably something else I messed up during my translation of the script, lol

**Comment by MetalES** [comment]
Yeah that might be because the new map instantly replace the old one, so on_draw is now applied only for the new map, maybe resizing the surface just to fit this little blank space would solve the thing

**Comment by wrightmat** [comment]
I tried doubling the surface size, and I still get the surface disappearing on the old map. I attempting to take a video, but my video capture program isn't cooperating.

**Comment by MetalES** [comment]
I'm gonna look at this, I didn't really take scrolling transition in parameters because I didn't use it in my project.

One workaround is, if you're using my "menu" with the tone system, is to start it in game instead of game:get_map()

**Comment by wrightmat** [comment]
I am using your "menu" system, but starting it with game instead has its own set of problems. Basically each time the map changes, a new overlay is created so the screen gets darker and darker. I tried to move the initialization of the system to game:on_started instead and I get a bunch of errors that seem to suggest an incorrect context.

**Comment by christopho** [comment]
I encountered the same bug while recording today's tutorials: https://github.com/christopho/solarus/issues/989
The workaround is indeed to use game:on_draw() instead of map:on_draw().

**Comment by MetalES** [comment]
Hmmm, thats because I restart the menu at each map change,
If you take a look at my game_manager, you might see that in game:on_map_changed, I restart the menu, so it is automatic, this is not needed anymore if you use game as the context for the tone system's menu, you just need to start it when the game start

**Comment by wrightmat** [comment]
Yeah, I tried to move the initialization to game:on_started and got a bunch of errors.

**Comment by MetalES** [comment]
The error might be related to maps because when a game starts, map is always nil, so it cannot do things right

**Comment by wrightmat** [comment]
I agree. I thought I had accounted for it, but apparently missed something. I ended up refactoring the code entirely, and it almost works now! The tone stays when then map changes, but the lights scroll with the map, so I've got to figure that out next.
