### ISSUE TITLE
Tower Of winds

### ISSUE THREAD

**Issue by Ezkazelda** [wrightmat/zbom#79]
Just in the first few moments of tower of winds I encountered some issues.
![screen shot 2017-01-12 at 6 18 06 pm](https://cloud.githubusercontent.com/assets/24845404/21913726/d1999ca2-d8f3-11e6-97c6-f8cfe8289c3d.png)
Both the enemies and the boulders don't hurt you here. Second, the boulder noise was very annoying and constant. Also, not sure if this is intentional or not. But it seemed like some doors were 1 sided and not connected to the other rooms

**Comment by wrightmat** [comment]
The boulders don't hit you there because they're moving strictly horizontally and you're below the line. There is nothing stopping the enemies from hitting you there - maybe you're just lucky. I just tested and they can hit me there.
I believe the doors you are referring to are the ones that move you up a floor. If you have an example other than that, feel free to post it.

**Comment by Ezkazelda** [comment]
The screen shot wasn't meant to show the damage not being taken, it was just meant as context to where this happened. Now it gets confusing. So all my post today were from the same gameplay session, and I think something might have happened during that gameplay session that messed up my game somehow. Because now when going back to all the previous parts that were messed up. The borders and enemies are hitting me( the doors were just misunderstanding on my part).

**Comment by MetalES** [comment]
I did encountered this too when the game was still in beta, how did I do that ? It is unknown, try to game over in the same room

**Comment by wrightmat** [comment]
If there was an error message, please pass that on. Otherwise I have no idea how to fix it as I didn't encounter it in any of my playthroughs.

**Comment by MetalES** [comment]
There were no error message and the way to trigger it was very hard (Using Cave of Ordeals, using a wrong warp and go game over into the tower of wind), it does just render Link invincible, it may has been fixed since and maybe there's another way to trigger it, I might investigate it, I'm still not at the Tower of Wind
