### ISSUE TITLE
Corrupted save if Sacred Grove not finished correctly

### ISSUE THREAD

**Issue by Renkineko** [wrightmat/zbom#86]
I just understood that when i was looking how to finish to complete the book of mudora item: i was looking at each dungeon place.

I did Sacred Grove as my first temple, when I killed Flora Gohma I tried to backtrack instead of going to the teleporter, as stated here: 

https://youtu.be/2QhvrUAeKao?t=1618

When I was against the entrance, the teleporter was not here anymore (the one inside the tree I mean). But I couldn't get out, because of the stream blocking the path. The stream should be on the other way, so you can't backtrack and are forced to go to the teleporter.

But you must also take in account that if the player save & quit, and do others temple, he can come back here later to get the missing variant of the book.

Why remove the chest when book of mudora variant > 1, and not just taking in account another boolean variable setup when opening this chest to remove it (so the player can't farm pages here)?

Anyway, I can fix that with the console, but for non dev, it's a run killer.

**Comment by wrightmat** [comment]
I fixed the streams issue by removing them as well when disabling the transporters.

As for the book variant, I think I had an old variable check in there that doesn't make sense. You're right, there's no need to check that variant > 1 and remove the chest, especially since I now I have the chest state saved in b1061. I think I'll remove that check entirely, unless you can think of a reason to keep it?

**Comment by Renkineko** [comment]
As I said, I don't see any reasons for this check to happen. If I'm looking at comments, they say it's to avoid the farm of the pages after the monkey stole the book (which never happened for me, nontheless, because i never finished properly this dungeon). I can do the test if you want: i remove the full check, then I go normally to the room and get the chest. Then i'll try to go again (but not during the livestream) to see what's happening and if i can farm it, even after the monkey stole the book (i suppose it'll happen if i get the chest normally... Real question is: will it restore all the book to me? Again, I can beta test it).

**Comment by wrightmat** [comment]
There's a separate check for the open state of the chest, so once it's been opened it can't be opened again. This variable will not revert when the monkey steals the page, because that decrements the Book of Mudora pages integer variable, and I'm pretty sure sets its own boolean as well. As I said, I think this was an artifact from a previous version of the script and I'm just going to remove it :)
